import { User } from './User';

export const USERS: User[] = [
  {
    userID: 'userID1',
    employeeID: 'employeeID1',
    firstName: 'Bill',
    lastName: 'Nye',
    payrollCode: 'QWERTY',
    email: 'scienceguy@billnye.com',
    accessLevel: 1,
    pointGoal: 100,
    currentPointTotal: 25,
  },
  {
    userID: 'userID1',
    employeeID: 'employeeID1',
    firstName: 'Bill',
    lastName: 'Nye',
    payrollCode: 'QWERTY',
    email: 'scienceguy@billnye.com',
    accessLevel: 1,
    pointGoal: 100,
    currentPointTotal: 25,
  },
  {
    userID: 'userID1',
    employeeID: 'employeeID1',
    firstName: 'Bill',
    lastName: 'Nye',
    payrollCode: 'QWERTY',
    email: 'scienceguy@billnye.com',
    accessLevel: 1,
    pointGoal: 100,
    currentPointTotal: 25,
  },
  {
    userID: 'userID1',
    employeeID: 'employeeID1',
    firstName: 'Bill',
    lastName: 'Nye',
    payrollCode: 'QWERTY',
    email: 'scienceguy@billnye.com',
    accessLevel: 1,
    pointGoal: 100,
    currentPointTotal: 25,
  },
  {
    userID: 'userID1',
    employeeID: 'employeeID1',
    firstName: 'Bill',
    lastName: 'Nye',
    payrollCode: 'QWERTY',
    email: 'scienceguy@billnye.com',
    accessLevel: 1,
    pointGoal: 100,
    currentPointTotal: 25,
  },
];
